# This is a basic workflow to help you get started with Actions

name: Build TF Lite for MacOS

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      TF_VERSION:
        description: 'Enter the tensorflow branch name on which the TF Lite binaries should be built.'
        required: true
        default: "r2.8"
      BUILD_OPTIONS:
        description: 'Enter the build options with which TF Lite binaries should be built.'
        required: false
        default: "-DTFLITE_ENABLE_XNNPACK=ON -DTFLITE_ENABLE_GPU=ON"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-macos:
    # The type of runner that the job will run on
    runs-on: macos-13

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    - name: Download and setup tensorflow
      run: |
        git clone https://github.com/tensorflow/tensorflow tensorflow_src
        cd tensorflow_src
        git checkout ${{ github.event.inputs.TF_VERSION }}
        cd ..
    
    - name: Build TF Lite
      run: |
        mkdir tflite_build
        cd tflite_build
        cmake ../tensorflow_src/tensorflow/lite/c ${{ github.event.inputs.BUILD_OPTIONS }}
        cmake --build .
        
    - name: output CWD
      run: ls -a tflite_build/
          
    - name: Upload TF Lite build 
      uses: actions/upload-artifact@v3
      with:
        name: libtensorflowlite_c-mac.dylib
        path: tflite_build/libtensorflowlite_c.dylib
